package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvResourcestype generated by hbm2java
 */
@Entity
@Table(name = "cv_resourcestype")
public class CvResourcestype implements java.io.Serializable {

	private int resourceTypeId;
	private String name;
	private String link;
	private Set<Sampleresources> sampleresourceses = new HashSet<Sampleresources>(
			0);

	public CvResourcestype() {
	}

	public CvResourcestype(int resourceTypeId, String name) {
		this.resourceTypeId = resourceTypeId;
		this.name = name;
	}

	public CvResourcestype(int resourceTypeId, String name, String link,
			Set<Sampleresources> sampleresourceses) {
		this.resourceTypeId = resourceTypeId;
		this.name = name;
		this.link = link;
		this.sampleresourceses = sampleresourceses;
	}

	@Id
	@Column(name = "resource_type_id", unique = true, nullable = false)
	public int getResourceTypeId() {
		return this.resourceTypeId;
	}

	public void setResourceTypeId(int resourceTypeId) {
		this.resourceTypeId = resourceTypeId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "link", length = 200)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvResourcestype")
	public Set<Sampleresources> getSampleresourceses() {
		return this.sampleresourceses;
	}

	public void setSampleresourceses(Set<Sampleresources> sampleresourceses) {
		this.sampleresourceses = sampleresourceses;
	}

}
