package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CvSamplingmethod generated by hbm2java
 */
@Entity
@Table(name = "cv_samplingmethod")
public class CvSamplingmethod implements java.io.Serializable {

	private int methodId;
	private String methodName;
	private String methodDescription;
	private String methodLink;
	private Set<Sample> samples = new HashSet<Sample>(0);

	public CvSamplingmethod() {
	}

	public CvSamplingmethod(int methodId, String methodName,
			String methodDescription) {
		this.methodId = methodId;
		this.methodName = methodName;
		this.methodDescription = methodDescription;
	}

	public CvSamplingmethod(int methodId, String methodName,
			String methodDescription, String methodLink, Set<Sample> samples) {
		this.methodId = methodId;
		this.methodName = methodName;
		this.methodDescription = methodDescription;
		this.methodLink = methodLink;
		this.samples = samples;
	}

	@Id
	@Column(name = "method_id", unique = true, nullable = false)
	@SequenceGenerator(name="cv_samplingmethod_method_id_seq",sequenceName="cv_samplingmethod_method_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="cv_samplingmethod_method_id_seq")
	public int getMethodId() {
		return this.methodId;
	}

	public void setMethodId(int methodId) {
		this.methodId = methodId;
	}

	@Column(name = "method_name", nullable = false, length = 80)
	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	@Column(name = "method_description", nullable = false)
	public String getMethodDescription() {
		return this.methodDescription;
	}

	public void setMethodDescription(String methodDescription) {
		this.methodDescription = methodDescription;
	}

	@Column(name = "method_link")
	public String getMethodLink() {
		return this.methodLink;
	}

	public void setMethodLink(String methodLink) {
		this.methodLink = methodLink;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvSamplingmethod")
	public Set<Sample> getSamples() {
		return this.samples;
	}

	public void setSamples(Set<Sample> samples) {
		this.samples = samples;
	}

}
