package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvSamplingfeature generated by hbm2java
 */
@Entity
@Table(name = "cv_samplingfeature")
public class CvSamplingfeature implements java.io.Serializable {

	private int featureId;
	private String name;
	private String definition;
	private String identifier;
	private Set<Sample> samples = new HashSet<Sample>(0);
	private Set<Samplingfeatures> samplingfeatureses = new HashSet<Samplingfeatures>(
			0);
	private Set<SampleFeaturesMapping> sampleFeaturesMappings = new HashSet<SampleFeaturesMapping>(
			0);

	public CvSamplingfeature() {
	}

	public CvSamplingfeature(int featureId) {
		this.featureId = featureId;
	}

	public CvSamplingfeature(int featureId, String name, String definition,
			String identifier, Set<Sample> samples,
			Set<Samplingfeatures> samplingfeatureses,
			Set<SampleFeaturesMapping> sampleFeaturesMappings) {
		this.featureId = featureId;
		this.name = name;
		this.definition = definition;
		this.identifier = identifier;
		this.samples = samples;
		this.samplingfeatureses = samplingfeatureses;
		this.sampleFeaturesMappings = sampleFeaturesMappings;
	}

	@Id
	@Column(name = "feature_id", unique = true, nullable = false)
	public int getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(int featureId) {
		this.featureId = featureId;
	}

	@Column(name = "name", length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "definition")
	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	@Column(name = "identifier")
	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvSamplingfeature")
	public Set<Sample> getSamples() {
		return this.samples;
	}

	public void setSamples(Set<Sample> samples) {
		this.samples = samples;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvSamplingfeature")
	public Set<Samplingfeatures> getSamplingfeatureses() {
		return this.samplingfeatureses;
	}

	public void setSamplingfeatureses(Set<Samplingfeatures> samplingfeatureses) {
		this.samplingfeatureses = samplingfeatureses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvSamplingfeature")
	public Set<SampleFeaturesMapping> getSampleFeaturesMappings() {
		return this.sampleFeaturesMappings;
	}

	public void setSampleFeaturesMappings(
			Set<SampleFeaturesMapping> sampleFeaturesMappings) {
		this.sampleFeaturesMappings = sampleFeaturesMappings;
	}

}
