package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Prefix generated by hbm2java
 */
@Entity
@Table(name = "prefix")
public class Prefix implements java.io.Serializable {

	private int objectId;
	private int version;
	private String prefix;
	private Date created;
	private Set<Registrant> registrants = new HashSet<Registrant>(0);
	private Set<Allocator> allocators = new HashSet<Allocator>(0);

	public Prefix() {
	}

	public Prefix(int objectId, String prefix, Date created) {
		this.objectId = objectId;
		this.prefix = prefix;
		this.created = created;
	}

	public Prefix(int objectId, String prefix, Date created,
			Set<Registrant> registrants, Set<Allocator> allocators) {
		this.objectId = objectId;
		this.prefix = prefix;
		this.created = created;
		this.registrants = registrants;
		this.allocators = allocators;
	}

	@Id
	@Column(name = "object_id", unique = true, nullable = false)
	public int getObjectId() {
		return this.objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "prefix", nullable = false, length = 50)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prefix")
	public Set<Registrant> getRegistrants() {
		return this.registrants;
	}

	public void setRegistrants(Set<Registrant> registrants) {
		this.registrants = registrants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prefix")
	public Set<Allocator> getAllocators() {
		return this.allocators;
	}

	public void setAllocators(Set<Allocator> allocators) {
		this.allocators = allocators;
	}

}
