package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registrant generated by hbm2java
 */
@Entity
@Table(name = "registrant")
public class Registrant implements java.io.Serializable {

	private int registrantId;
	private Allocator allocator;
	private Prefix prefix;
	private String email;
	private String username;
	private Date created;
	private int igsnQuotaAllowed;
	private int igsnQuotaUsed;
	private Boolean isActive;
	private String name;
	private String password;
	private Date updated;
	private Set<Sample> samples = new HashSet<Sample>(0);

	public Registrant() {
	}

	public Registrant(int registrantId, Allocator allocator, Prefix prefix,
			String email, String username, int igsnQuotaAllowed,
			int igsnQuotaUsed, String name, String password, Date updated) {
		this.registrantId = registrantId;
		this.allocator = allocator;
		this.prefix = prefix;
		this.email = email;
		this.username = username;
		this.igsnQuotaAllowed = igsnQuotaAllowed;
		this.igsnQuotaUsed = igsnQuotaUsed;
		this.name = name;
		this.password = password;
		this.updated = updated;
	}

	public Registrant(int registrantId, Allocator allocator, Prefix prefix,
			String email, String username, Date created, int igsnQuotaAllowed,
			int igsnQuotaUsed, Boolean isActive, String name, String password,
			Date updated, Set<Sample> samples) {
		this.registrantId = registrantId;
		this.allocator = allocator;
		this.prefix = prefix;
		this.email = email;
		this.username = username;
		this.created = created;
		this.igsnQuotaAllowed = igsnQuotaAllowed;
		this.igsnQuotaUsed = igsnQuotaUsed;
		this.isActive = isActive;
		this.name = name;
		this.password = password;
		this.updated = updated;
		this.samples = samples;
	}

	@Id
	@Column(name = "registrant_id", unique = true, nullable = false)
	@SequenceGenerator(name="registrant_registrant_id_seq",sequenceName="registrant_registrant_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="registrant_registrant_id_seq")
	public int getRegistrantId() {
		return this.registrantId;
	}

	public void setRegistrantId(int registrantId) {
		this.registrantId = registrantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "allocator", nullable = false)
	public Allocator getAllocator() {
		return this.allocator;
	}

	public void setAllocator(Allocator allocator) {
		this.allocator = allocator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "registrant_prefix", nullable = false)
	public Prefix getPrefix() {
		return this.prefix;
	}

	public void setPrefix(Prefix prefix) {
		this.prefix = prefix;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", nullable = false, length = 80)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 29)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "igsn_quota_allowed", nullable = false)
	public int getIgsnQuotaAllowed() {
		return this.igsnQuotaAllowed;
	}

	public void setIgsnQuotaAllowed(int igsnQuotaAllowed) {
		this.igsnQuotaAllowed = igsnQuotaAllowed;
	}

	@Column(name = "igsn_quota_used", nullable = false)
	public int getIgsnQuotaUsed() {
		return this.igsnQuotaUsed;
	}

	public void setIgsnQuotaUsed(int igsnQuotaUsed) {
		this.igsnQuotaUsed = igsnQuotaUsed;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", nullable = false, length = 29)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "registrant")
	public Set<Sample> getSamples() {
		return this.samples;
	}

	public void setSamples(Set<Sample> samples) {
		this.samples = samples;
	}

}
