package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Samplecollector generated by hbm2java
 */
@Entity
@Table(name = "samplecollector")
public class Samplecollector implements java.io.Serializable {

	private int collectorId;
	private Sample sample;
	private String collector;

	public Samplecollector() {
	}

	public Samplecollector(int collectorId, Sample sample, String collector) {
		this.collectorId = collectorId;
		this.sample = sample;
		this.collector = collector;
	}

	@Id
	@Column(name = "collector_id", unique = true, nullable = false)
	public int getCollectorId() {
		return this.collectorId;
	}

	public void setCollectorId(int collectorId) {
		this.collectorId = collectorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_id", nullable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@Column(name = "collector", nullable = false)
	public String getCollector() {
		return this.collector;
	}

	public void setCollector(String collector) {
		this.collector = collector;
	}

}
