package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Samplegroupdesc generated by hbm2java
 */
@Entity
@Table(name = "samplegroupdesc")
public class Samplegroupdesc implements java.io.Serializable {

	private int groupId;
	private String groupDescription;
	private Set<Samplegroup> samplegroups = new HashSet<Samplegroup>(0);

	public Samplegroupdesc() {
	}

	public Samplegroupdesc(int groupId) {
		this.groupId = groupId;
	}

	public Samplegroupdesc(int groupId, String groupDescription,
			Set<Samplegroup> samplegroups) {
		this.groupId = groupId;
		this.groupDescription = groupDescription;
		this.samplegroups = samplegroups;
	}

	@Id
	@Column(name = "group_id", unique = true, nullable = false)
	@SequenceGenerator(name="samplegroupdesc_group_id_seq",sequenceName="samplegroupdesc_group_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="samplegroupdesc_group_id_seq")
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_description")
	public String getGroupDescription() {
		return this.groupDescription;
	}

	public void setGroupDescription(String groupDescription) {
		this.groupDescription = groupDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "samplegroupdesc")
	public Set<Samplegroup> getSamplegroups() {
		return this.samplegroups;
	}

	public void setSamplegroups(Set<Samplegroup> samplegroups) {
		this.samplegroups = samplegroups;
	}

}
