package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Samplegroup generated by hbm2java
 */
@Entity
@Table(name = "samplegroup")
public class Samplegroup implements java.io.Serializable {

	private int sampleGroupId;
	private Sample sample;
	private Samplegroupdesc samplegroupdesc;

	public Samplegroup() {
	}

	public Samplegroup(int sampleGroupId, Sample sample,
			Samplegroupdesc samplegroupdesc) {
		this.sampleGroupId = sampleGroupId;
		this.sample = sample;
		this.samplegroupdesc = samplegroupdesc;
	}

	@Id
	@Column(name = "sample_group_id", unique = true, nullable = false)
	public int getSampleGroupId() {
		return this.sampleGroupId;
	}

	public void setSampleGroupId(int sampleGroupId) {
		this.sampleGroupId = sampleGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_id", nullable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false)
	public Samplegroupdesc getSamplegroupdesc() {
		return this.samplegroupdesc;
	}

	public void setSamplegroupdesc(Samplegroupdesc samplegroupdesc) {
		this.samplegroupdesc = samplegroupdesc;
	}

}
