package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Samplingfeatures generated by hbm2java
 */
@Entity
@Table(name = "samplingfeatures")
public class Samplingfeatures implements java.io.Serializable {

	private int featureId;
	private CvSamplingfeature cvSamplingfeature;
	private CvSpatialreferences cvSpatialreferences;
	private String featureName;
	private Serializable featureLocalXy;
	private Serializable featureLatlon;
	private Serializable featureLatlonEnd;
	private String featureLocality;

	public Samplingfeatures() {
	}

	public Samplingfeatures(int featureId, String featureName) {
		this.featureId = featureId;
		this.featureName = featureName;
	}

	public Samplingfeatures(int featureId, CvSamplingfeature cvSamplingfeature,
			CvSpatialreferences cvSpatialreferences, String featureName,
			Serializable featureLocalXy, Serializable featureLatlon,
			Serializable featureLatlonEnd, String featureLocality) {
		this.featureId = featureId;
		this.cvSamplingfeature = cvSamplingfeature;
		this.cvSpatialreferences = cvSpatialreferences;
		this.featureName = featureName;
		this.featureLocalXy = featureLocalXy;
		this.featureLatlon = featureLatlon;
		this.featureLatlonEnd = featureLatlonEnd;
		this.featureLocality = featureLocality;
	}

	@Id
	@Column(name = "feature_id", unique = true, nullable = false)
	@SequenceGenerator(name="samplingfeatures_feature_id_seq",sequenceName="samplingfeatures_feature_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="samplingfeatures_feature_id_seq")
	public int getFeatureId() {
		return this.featureId;
	}

	public void setFeatureId(int featureId) {
		this.featureId = featureId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feature_type")
	public CvSamplingfeature getCvSamplingfeature() {
		return this.cvSamplingfeature;
	}

	public void setCvSamplingfeature(CvSamplingfeature cvSamplingfeature) {
		this.cvSamplingfeature = cvSamplingfeature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feature_srs")
	public CvSpatialreferences getCvSpatialreferences() {
		return this.cvSpatialreferences;
	}

	public void setCvSpatialreferences(CvSpatialreferences cvSpatialreferences) {
		this.cvSpatialreferences = cvSpatialreferences;
	}

	@Column(name = "feature_name", nullable = false, length = 100)
	public String getFeatureName() {
		return this.featureName;
	}

	public void setFeatureName(String featureName) {
		this.featureName = featureName;
	}

	@Column(name = "feature_local_xy")
	public Serializable getFeatureLocalXy() {
		return this.featureLocalXy;
	}

	public void setFeatureLocalXy(Serializable featureLocalXy) {
		this.featureLocalXy = featureLocalXy;
	}

	@Column(name = "feature_latlon")
	public Serializable getFeatureLatlon() {
		return this.featureLatlon;
	}

	public void setFeatureLatlon(Serializable featureLatlon) {
		this.featureLatlon = featureLatlon;
	}

	@Column(name = "feature_latlon_end")
	public Serializable getFeatureLatlonEnd() {
		return this.featureLatlonEnd;
	}

	public void setFeatureLatlonEnd(Serializable featureLatlonEnd) {
		this.featureLatlonEnd = featureLatlonEnd;
	}

	@Column(name = "feature_locality", length = 150)
	public String getFeatureLocality() {
		return this.featureLocality;
	}

	public void setFeatureLocality(String featureLocality) {
		this.featureLocality = featureLocality;
	}

}
