package org.csiro.igsn.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sampleresources generated by hbm2java
 */
@Entity
@Table(name = "sampleresources")
public class Sampleresources implements java.io.Serializable {

	private int sampleResourceId;
	private CvResourcestype cvResourcestype;
	private Sample sample;
	private String resourceName;
	private String resourcePath;
	private String addedBy;
	private Date addedDate;

	public Sampleresources() {
	}

	public Sampleresources(int sampleResourceId,
			CvResourcestype cvResourcestype, Sample sample) {
		this.sampleResourceId = sampleResourceId;
		this.cvResourcestype = cvResourcestype;
		this.sample = sample;
	}

	public Sampleresources(int sampleResourceId,
			CvResourcestype cvResourcestype, Sample sample,
			String resourceName, String resourcePath, String addedBy,
			Date addedDate) {
		this.sampleResourceId = sampleResourceId;
		this.cvResourcestype = cvResourcestype;
		this.sample = sample;
		this.resourceName = resourceName;
		this.resourcePath = resourcePath;
		this.addedBy = addedBy;
		this.addedDate = addedDate;
	}

	@Id
	@Column(name = "sample_resource_id", unique = true, nullable = false)
	@SequenceGenerator(name="sampleresources_sample_resource_id_seq",sequenceName="sampleresources_sample_resource_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="sampleresources_sample_resource_id_seq")
	public int getSampleResourceId() {
		return this.sampleResourceId;
	}

	public void setSampleResourceId(int sampleResourceId) {
		this.sampleResourceId = sampleResourceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_type", nullable = false)
	public CvResourcestype getCvResourcestype() {
		return this.cvResourcestype;
	}

	public void setCvResourcestype(CvResourcestype cvResourcestype) {
		this.cvResourcestype = cvResourcestype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_id", nullable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@Column(name = "resource_name", length = 150)
	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	@Column(name = "resource_path", length = 500)
	public String getResourcePath() {
		return this.resourcePath;
	}

	public void setResourcePath(String resourcePath) {
		this.resourcePath = resourcePath;
	}

	@Column(name = "added_by", length = 200)
	public String getAddedBy() {
		return this.addedBy;
	}

	public void setAddedBy(String addedBy) {
		this.addedBy = addedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "added_date", length = 29)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

}
