//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 02:01:42 PM AWST 
//

 @javax.xml.bind.annotation.XmlSchema (
      xmlns = { 
        @javax.xml.bind.annotation.XmlNs(prefix = "oai_dc", 
                   namespaceURI="http://www.openarchives.org/OAI/2.0/oai_dc/"),

        @javax.xml.bind.annotation.XmlNs(prefix="dc",
                   namespaceURI="http://purl.org/dc/elements/1.1/")
      }
    )
package org.csiro.oai.dc.binding;
