//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 02:04:33 PM AWST 
//


package org.csiro.igsn.bindings.allocation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csiro.igsn.bindings.allocation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csiro.igsn.bindings.allocation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Samples }
     * 
     */
    public Samples createSamples() {
        return new Samples();
    }

    /**
     * Create an instance of {@link Samples.Sample }
     * 
     */
    public Samples.Sample createSamplesSample() {
        return new Samples.Sample();
    }

    /**
     * Create an instance of {@link Samples.Sample.RelatedResources }
     * 
     */
    public Samples.Sample.RelatedResources createSamplesSampleRelatedResources() {
        return new Samples.Sample.RelatedResources();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleCuration }
     * 
     */
    public Samples.Sample.SampleCuration createSamplesSampleSampleCuration() {
        return new Samples.Sample.SampleCuration();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleCuration.Curator }
     * 
     */
    public Samples.Sample.SampleCuration.Curator createSamplesSampleSampleCurationCurator() {
        return new Samples.Sample.SampleCuration.Curator();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleCuration.Curator.CurationTime }
     * 
     */
    public Samples.Sample.SampleCuration.Curator.CurationTime createSamplesSampleSampleCurationCuratorCurationTime() {
        return new Samples.Sample.SampleCuration.Curator.CurationTime();
    }

    /**
     * Create an instance of {@link Samples.Sample.SamplingFeatures }
     * 
     */
    public Samples.Sample.SamplingFeatures createSamplesSampleSamplingFeatures() {
        return new Samples.Sample.SamplingFeatures();
    }

    /**
     * Create an instance of {@link Samples.Sample.SamplingFeatures.Feature }
     * 
     */
    public Samples.Sample.SamplingFeatures.Feature createSamplesSampleSamplingFeaturesFeature() {
        return new Samples.Sample.SamplingFeatures.Feature();
    }

    /**
     * Create an instance of {@link Samples.Sample.SamplingFeatures.Feature.FeatureLocation }
     * 
     */
    public Samples.Sample.SamplingFeatures.Feature.FeatureLocation createSamplesSampleSamplingFeaturesFeatureFeatureLocation() {
        return new Samples.Sample.SamplingFeatures.Feature.FeatureLocation();
    }

    /**
     * Create an instance of {@link Samples.LogElement }
     * 
     */
    public Samples.LogElement createSamplesLogElement() {
        return new Samples.LogElement();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleNumber }
     * 
     */
    public Samples.Sample.SampleNumber createSamplesSampleSampleNumber() {
        return new Samples.Sample.SampleNumber();
    }

    /**
     * Create an instance of {@link Samples.Sample.OtherNames }
     * 
     */
    public Samples.Sample.OtherNames createSamplesSampleOtherNames() {
        return new Samples.Sample.OtherNames();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleTypes }
     * 
     */
    public Samples.Sample.SampleTypes createSamplesSampleSampleTypes() {
        return new Samples.Sample.SampleTypes();
    }

    /**
     * Create an instance of {@link Samples.Sample.MaterialTypes }
     * 
     */
    public Samples.Sample.MaterialTypes createSamplesSampleMaterialTypes() {
        return new Samples.Sample.MaterialTypes();
    }

    /**
     * Create an instance of {@link Samples.Sample.Classification }
     * 
     */
    public Samples.Sample.Classification createSamplesSampleClassification() {
        return new Samples.Sample.Classification();
    }

    /**
     * Create an instance of {@link Samples.Sample.SamplingLocation }
     * 
     */
    public Samples.Sample.SamplingLocation createSamplesSampleSamplingLocation() {
        return new Samples.Sample.SamplingLocation();
    }

    /**
     * Create an instance of {@link Samples.Sample.SamplingTime }
     * 
     */
    public Samples.Sample.SamplingTime createSamplesSampleSamplingTime() {
        return new Samples.Sample.SamplingTime();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleCollectors }
     * 
     */
    public Samples.Sample.SampleCollectors createSamplesSampleSampleCollectors() {
        return new Samples.Sample.SampleCollectors();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleSize }
     * 
     */
    public Samples.Sample.SampleSize createSamplesSampleSampleSize() {
        return new Samples.Sample.SampleSize();
    }

    /**
     * Create an instance of {@link Samples.Sample.RelatedResources.RelatedResourceIdentifier }
     * 
     */
    public Samples.Sample.RelatedResources.RelatedResourceIdentifier createSamplesSampleRelatedResourcesRelatedResourceIdentifier() {
        return new Samples.Sample.RelatedResources.RelatedResourceIdentifier();
    }

    /**
     * Create an instance of {@link Samples.Sample.SampleCuration.Curator.CurationTime.TimePeriod }
     * 
     */
    public Samples.Sample.SampleCuration.Curator.CurationTime.TimePeriod createSamplesSampleSampleCurationCuratorCurationTimeTimePeriod() {
        return new Samples.Sample.SampleCuration.Curator.CurationTime.TimePeriod();
    }

    /**
     * Create an instance of {@link Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Latlon }
     * 
     */
    public Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Latlon createSamplesSampleSamplingFeaturesFeatureFeatureLocationLatlon() {
        return new Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Latlon();
    }

    /**
     * Create an instance of {@link Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Localxy }
     * 
     */
    public Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Localxy createSamplesSampleSamplingFeaturesFeatureFeatureLocationLocalxy() {
        return new Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Localxy();
    }

    /**
     * Create an instance of {@link Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Bbox }
     * 
     */
    public Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Bbox createSamplesSampleSamplingFeaturesFeatureFeatureLocationBbox() {
        return new Samples.Sample.SamplingFeatures.Feature.FeatureLocation.Bbox();
    }

}
