//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 02:05:21 PM AWST 
//


package org.csiro.igsn.bindings.registry;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.csiro.igsn.bindings.registry package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.csiro.igsn.bindings.registry
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sample }
     * 
     */
    public Sample createSample() {
        return new Sample();
    }

    /**
     * Create an instance of {@link Sample.Log }
     * 
     */
    public Sample.Log createSampleLog() {
        return new Sample.Log();
    }

    /**
     * Create an instance of {@link Sample.RelatedResourceIdentifiers }
     * 
     */
    public Sample.RelatedResourceIdentifiers createSampleRelatedResourceIdentifiers() {
        return new Sample.RelatedResourceIdentifiers();
    }

    /**
     * Create an instance of {@link Sample.Registrant }
     * 
     */
    public Sample.Registrant createSampleRegistrant() {
        return new Sample.Registrant();
    }

    /**
     * Create an instance of {@link Sample.SampleNumber }
     * 
     */
    public Sample.SampleNumber createSampleSampleNumber() {
        return new Sample.SampleNumber();
    }

    /**
     * Create an instance of {@link Sample.Log.LogElement }
     * 
     */
    public Sample.Log.LogElement createSampleLogLogElement() {
        return new Sample.Log.LogElement();
    }

    /**
     * Create an instance of {@link Sample.RelatedResourceIdentifiers.RelatedIdentifier }
     * 
     */
    public Sample.RelatedResourceIdentifiers.RelatedIdentifier createSampleRelatedResourceIdentifiersRelatedIdentifier() {
        return new Sample.RelatedResourceIdentifiers.RelatedIdentifier();
    }

    /**
     * Create an instance of {@link Sample.Registrant.NameIdentifier }
     * 
     */
    public Sample.Registrant.NameIdentifier createSampleRegistrantNameIdentifier() {
        return new Sample.Registrant.NameIdentifier();
    }

}
