//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.12 at 02:05:21 PM AWST 
//


package org.csiro.igsn.bindings.registry;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sampleNumber">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="identifierType" use="required" type="{http://igsn.org/schema/kernel-v.1.1}identifierType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="registrant">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="registrantName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="nameIdentifier" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="nameIdentifierScheme" use="required" type="{http://igsn.org/schema/kernel-v.1.1}nameIdentifier" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="relatedResourceIdentifiers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="relatedIdentifier" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="relatedIdentifierType" type="{http://igsn.org/schema/kernel-v.1.1}relatedIdentifierType" />
 *                           &lt;attribute name="relationType" type="{http://igsn.org/schema/kernel-v.1.1}relationType" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="log">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="logElement" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="event" use="required" type="{http://igsn.org/schema/kernel-v.1.1}eventType" />
 *                           &lt;attribute name="timeStamp" use="required" type="{http://igsn.org/schema/kernel-v.1.1}W3CDTFdate" />
 *                           &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sampleNumber",
    "registrant",
    "relatedResourceIdentifiers",
    "log"
})
@XmlRootElement(name = "sample")
public class Sample {

    @XmlElement(required = true)
    protected Sample.SampleNumber sampleNumber;
    @XmlElement(required = true)
    protected Sample.Registrant registrant;
    protected Sample.RelatedResourceIdentifiers relatedResourceIdentifiers;
    @XmlElement(required = true)
    protected Sample.Log log;

    /**
     * Gets the value of the sampleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Sample.SampleNumber }
     *     
     */
    public Sample.SampleNumber getSampleNumber() {
        return sampleNumber;
    }

    /**
     * Sets the value of the sampleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sample.SampleNumber }
     *     
     */
    public void setSampleNumber(Sample.SampleNumber value) {
        this.sampleNumber = value;
    }

    /**
     * Gets the value of the registrant property.
     * 
     * @return
     *     possible object is
     *     {@link Sample.Registrant }
     *     
     */
    public Sample.Registrant getRegistrant() {
        return registrant;
    }

    /**
     * Sets the value of the registrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sample.Registrant }
     *     
     */
    public void setRegistrant(Sample.Registrant value) {
        this.registrant = value;
    }

    /**
     * Gets the value of the relatedResourceIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link Sample.RelatedResourceIdentifiers }
     *     
     */
    public Sample.RelatedResourceIdentifiers getRelatedResourceIdentifiers() {
        return relatedResourceIdentifiers;
    }

    /**
     * Sets the value of the relatedResourceIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sample.RelatedResourceIdentifiers }
     *     
     */
    public void setRelatedResourceIdentifiers(Sample.RelatedResourceIdentifiers value) {
        this.relatedResourceIdentifiers = value;
    }

    /**
     * Gets the value of the log property.
     * 
     * @return
     *     possible object is
     *     {@link Sample.Log }
     *     
     */
    public Sample.Log getLog() {
        return log;
    }

    /**
     * Sets the value of the log property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sample.Log }
     *     
     */
    public void setLog(Sample.Log value) {
        this.log = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="logElement" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="event" use="required" type="{http://igsn.org/schema/kernel-v.1.1}eventType" />
     *                 &lt;attribute name="timeStamp" use="required" type="{http://igsn.org/schema/kernel-v.1.1}W3CDTFdate" />
     *                 &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "logElement"
    })
    public static class Log {

        @XmlElement(required = true)
        protected List<Sample.Log.LogElement> logElement;

        /**
         * Gets the value of the logElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the logElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLogElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Sample.Log.LogElement }
         * 
         * 
         */
        public List<Sample.Log.LogElement> getLogElement() {
            if (logElement == null) {
                logElement = new ArrayList<Sample.Log.LogElement>();
            }
            return this.logElement;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="event" use="required" type="{http://igsn.org/schema/kernel-v.1.1}eventType" />
         *       &lt;attribute name="timeStamp" use="required" type="{http://igsn.org/schema/kernel-v.1.1}W3CDTFdate" />
         *       &lt;attribute name="comment" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class LogElement {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "event", required = true)
            protected EventType event;
            @XmlAttribute(name = "timeStamp", required = true)
            protected String timeStamp;
            @XmlAttribute(name = "comment")
            protected String comment;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the event property.
             * 
             * @return
             *     possible object is
             *     {@link EventType }
             *     
             */
            public EventType getEvent() {
                return event;
            }

            /**
             * Sets the value of the event property.
             * 
             * @param value
             *     allowed object is
             *     {@link EventType }
             *     
             */
            public void setEvent(EventType value) {
                this.event = value;
            }

            /**
             * Gets the value of the timeStamp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTimeStamp() {
                return timeStamp;
            }

            /**
             * Sets the value of the timeStamp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTimeStamp(String value) {
                this.timeStamp = value;
            }

            /**
             * Gets the value of the comment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComment() {
                return comment;
            }

            /**
             * Sets the value of the comment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComment(String value) {
                this.comment = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="registrantName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="nameIdentifier" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="nameIdentifierScheme" use="required" type="{http://igsn.org/schema/kernel-v.1.1}nameIdentifier" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "registrantName",
        "nameIdentifier"
    })
    public static class Registrant {

        @XmlElement(required = true)
        protected String registrantName;
        protected Sample.Registrant.NameIdentifier nameIdentifier;

        /**
         * Gets the value of the registrantName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistrantName() {
            return registrantName;
        }

        /**
         * Sets the value of the registrantName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistrantName(String value) {
            this.registrantName = value;
        }

        /**
         * Gets the value of the nameIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link Sample.Registrant.NameIdentifier }
         *     
         */
        public Sample.Registrant.NameIdentifier getNameIdentifier() {
            return nameIdentifier;
        }

        /**
         * Sets the value of the nameIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link Sample.Registrant.NameIdentifier }
         *     
         */
        public void setNameIdentifier(Sample.Registrant.NameIdentifier value) {
            this.nameIdentifier = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="nameIdentifierScheme" use="required" type="{http://igsn.org/schema/kernel-v.1.1}nameIdentifier" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class NameIdentifier {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "nameIdentifierScheme", required = true)
            protected org.csiro.igsn.bindings.registry.NameIdentifier nameIdentifierScheme;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the nameIdentifierScheme property.
             * 
             * @return
             *     possible object is
             *     {@link org.csiro.igsn.bindings.registry.NameIdentifier }
             *     
             */
            public org.csiro.igsn.bindings.registry.NameIdentifier getNameIdentifierScheme() {
                return nameIdentifierScheme;
            }

            /**
             * Sets the value of the nameIdentifierScheme property.
             * 
             * @param value
             *     allowed object is
             *     {@link org.csiro.igsn.bindings.registry.NameIdentifier }
             *     
             */
            public void setNameIdentifierScheme(org.csiro.igsn.bindings.registry.NameIdentifier value) {
                this.nameIdentifierScheme = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="relatedIdentifier" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="relatedIdentifierType" type="{http://igsn.org/schema/kernel-v.1.1}relatedIdentifierType" />
     *                 &lt;attribute name="relationType" type="{http://igsn.org/schema/kernel-v.1.1}relationType" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relatedIdentifier"
    })
    public static class RelatedResourceIdentifiers {

        @XmlElement(required = true)
        protected List<Sample.RelatedResourceIdentifiers.RelatedIdentifier> relatedIdentifier;

        /**
         * Gets the value of the relatedIdentifier property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relatedIdentifier property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelatedIdentifier().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Sample.RelatedResourceIdentifiers.RelatedIdentifier }
         * 
         * 
         */
        public List<Sample.RelatedResourceIdentifiers.RelatedIdentifier> getRelatedIdentifier() {
            if (relatedIdentifier == null) {
                relatedIdentifier = new ArrayList<Sample.RelatedResourceIdentifiers.RelatedIdentifier>();
            }
            return this.relatedIdentifier;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="relatedIdentifierType" type="{http://igsn.org/schema/kernel-v.1.1}relatedIdentifierType" />
         *       &lt;attribute name="relationType" type="{http://igsn.org/schema/kernel-v.1.1}relationType" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class RelatedIdentifier {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "relatedIdentifierType")
            protected RelatedIdentifierType relatedIdentifierType;
            @XmlAttribute(name = "relationType")
            protected RelationType relationType;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the relatedIdentifierType property.
             * 
             * @return
             *     possible object is
             *     {@link RelatedIdentifierType }
             *     
             */
            public RelatedIdentifierType getRelatedIdentifierType() {
                return relatedIdentifierType;
            }

            /**
             * Sets the value of the relatedIdentifierType property.
             * 
             * @param value
             *     allowed object is
             *     {@link RelatedIdentifierType }
             *     
             */
            public void setRelatedIdentifierType(RelatedIdentifierType value) {
                this.relatedIdentifierType = value;
            }

            /**
             * Gets the value of the relationType property.
             * 
             * @return
             *     possible object is
             *     {@link RelationType }
             *     
             */
            public RelationType getRelationType() {
                return relationType;
            }

            /**
             * Sets the value of the relationType property.
             * 
             * @param value
             *     allowed object is
             *     {@link RelationType }
             *     
             */
            public void setRelationType(RelationType value) {
                this.relationType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="identifierType" use="required" type="{http://igsn.org/schema/kernel-v.1.1}identifierType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class SampleNumber {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "identifierType", required = true)
        protected IdentifierType identifierType;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the identifierType property.
         * 
         * @return
         *     possible object is
         *     {@link IdentifierType }
         *     
         */
        public IdentifierType getIdentifierType() {
            return identifierType;
        }

        /**
         * Sets the value of the identifierType property.
         * 
         * @param value
         *     allowed object is
         *     {@link IdentifierType }
         *     
         */
        public void setIdentifierType(IdentifierType value) {
            this.identifierType = value;
        }

    }

}
