package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvRelatedIdentifiertype generated by hbm2java
 */
@Entity
@Table(name = "cv_related_identifiertype")
@NamedQueries({
	@NamedQuery(
			name="CvRelatedIdentifiertype.searchByRelatedidentifiertype",
		    query="SELECT r FROM CvRelatedIdentifiertype r where r.relatedidentifiertype = :relatedidentifiertype"
	)
})	
public class CvRelatedIdentifiertype implements java.io.Serializable {

	private int objectid;
	private String relatedidentifiertype;
	private Set<Sampleresources> sampleresourceses = new HashSet<Sampleresources>(
			0);

	public CvRelatedIdentifiertype() {
	}

	public CvRelatedIdentifiertype(int objectid, String relatedidentifiertype) {
		this.objectid = objectid;
		this.relatedidentifiertype = relatedidentifiertype;
	}

	public CvRelatedIdentifiertype(int objectid, String relatedidentifiertype,
			Set<Sampleresources> sampleresourceses) {
		this.objectid = objectid;
		this.relatedidentifiertype = relatedidentifiertype;
		this.sampleresourceses = sampleresourceses;
	}

	@Id
	@Column(name = "objectid", unique = true, nullable = false)
	public int getObjectid() {
		return this.objectid;
	}

	public void setObjectid(int objectid) {
		this.objectid = objectid;
	}

	@Column(name = "relatedidentifiertype", nullable = false, length = 20)
	public String getRelatedidentifiertype() {
		return this.relatedidentifiertype;
	}

	public void setRelatedidentifiertype(String relatedidentifiertype) {
		this.relatedidentifiertype = relatedidentifiertype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvRelatedIdentifiertype")
	public Set<Sampleresources> getSampleresourceses() {
		return this.sampleresourceses;
	}

	public void setSampleresourceses(Set<Sampleresources> sampleresourceses) {
		this.sampleresourceses = sampleresourceses;
	}

}
