package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CvSamplingfeature generated by hbm2java
 */
@Entity
@Table(name = "cv_samplingfeature")
public class CvSamplingfeature implements java.io.Serializable {

	private int featureid;
	private String name;
	private String definition;
	private String identifier;
	private Set<Samplingfeatures> samplingfeatureses = new HashSet<Samplingfeatures>(
			0);

	public CvSamplingfeature() {
	}

	public CvSamplingfeature(int featureid, String identifier) {
		this.featureid = featureid;
		this.identifier = identifier;
	}

	public CvSamplingfeature(int featureid, String name, String definition,
			String identifier, Set<Samplingfeatures> samplingfeatureses) {
		this.featureid = featureid;
		this.name = name;
		this.definition = definition;
		this.identifier = identifier;
		this.samplingfeatureses = samplingfeatureses;
	}

	@Id
	@Column(name = "featureid", unique = true, nullable = false)
	public int getFeatureid() {
		return this.featureid;
	}

	public void setFeatureid(int featureid) {
		this.featureid = featureid;
	}

	@Column(name = "name", length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "definition")
	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	@Column(name = "identifier", nullable = false)
	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cvSamplingfeature")
	public Set<Samplingfeatures> getSamplingfeatureses() {
		return this.samplingfeatureses;
	}

	public void setSamplingfeatureses(Set<Samplingfeatures> samplingfeatureses) {
		this.samplingfeatureses = samplingfeatureses;
	}

}
