package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * CvSampletype generated by hbm2java
 */
@Entity
@Table(name = "cv_sampletype", uniqueConstraints = @UniqueConstraint(columnNames = "sampletypeidentifier"))
@NamedQueries({
	@NamedQuery(
			name="CvSampletype.searchBySampleType",
		    query="SELECT r FROM CvSampletype r where r.sampletypeidentifier = :sampletypeidentifier"
	),
	@NamedQuery(
			name="CvSampletype.getList",
		    query="SELECT r FROM CvSampletype r"
	)
})	
public class CvSampletype implements java.io.Serializable {

	private int sampletypeid;
	private String sampletypeidentifier;
	private String sampletypedefinition;
	private Set<Sample> samples = new HashSet<Sample>(0);

	public CvSampletype() {
	}

	public CvSampletype(int sampletypeid, String sampletypeidentifier) {
		this.sampletypeid = sampletypeid;
		this.sampletypeidentifier = sampletypeidentifier;
	}

	public CvSampletype(int sampletypeid, String sampletypeidentifier,
			String sampletypedefinition, Set<Sample> samples) {
		this.sampletypeid = sampletypeid;
		this.sampletypeidentifier = sampletypeidentifier;
		this.sampletypedefinition = sampletypedefinition;
		this.samples = samples;
	}

	@Id
	@Column(name = "sampletypeid", unique = true, nullable = false)
	public int getSampletypeid() {
		return this.sampletypeid;
	}

	public void setSampletypeid(int sampletypeid) {
		this.sampletypeid = sampletypeid;
	}

	@Column(name = "sampletypeidentifier", unique = true, nullable = false)
	public String getSampletypeidentifier() {
		return this.sampletypeidentifier;
	}

	public void setSampletypeidentifier(String sampletypeidentifier) {
		this.sampletypeidentifier = sampletypeidentifier;
	}

	@Column(name = "sampletypedefinition")
	public String getSampletypedefinition() {
		return this.sampletypedefinition;
	}

	public void setSampletypedefinition(String sampletypedefinition) {
		this.sampletypedefinition = sampletypedefinition;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "cvSampletypes")
	@JsonIgnore
	public Set<Sample> getSamples() {
		return this.samples;
	}

	public void setSamples(Set<Sample> samples) {
		this.samples = samples;
	}

}
