package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GeographyColumns generated by hbm2java
 */
@Entity
@Table(name = "geography_columns")
public class GeographyColumns implements java.io.Serializable {

	private GeographyColumnsId id;

	public GeographyColumns() {
	}

	public GeographyColumns(GeographyColumnsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "FTableCatalog", column = @Column(name = "f_table_catalog")),
			@AttributeOverride(name = "FTableSchema", column = @Column(name = "f_table_schema")),
			@AttributeOverride(name = "FTableName", column = @Column(name = "f_table_name")),
			@AttributeOverride(name = "FGeographyColumn", column = @Column(name = "f_geography_column")),
			@AttributeOverride(name = "coordDimension", column = @Column(name = "coord_dimension")),
			@AttributeOverride(name = "srid", column = @Column(name = "srid")),
			@AttributeOverride(name = "type", column = @Column(name = "type")) })
	public GeographyColumnsId getId() {
		return this.id;
	}

	public void setId(GeographyColumnsId id) {
		this.id = id;
	}

}
