package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GeometryColumns generated by hbm2java
 */
@Entity
@Table(name = "geometry_columns")
public class GeometryColumns implements java.io.Serializable {

	private GeometryColumnsId id;

	public GeometryColumns() {
	}

	public GeometryColumns(GeometryColumnsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "FTableCatalog", column = @Column(name = "f_table_catalog", length = 256)),
			@AttributeOverride(name = "FTableSchema", column = @Column(name = "f_table_schema", length = 256)),
			@AttributeOverride(name = "FTableName", column = @Column(name = "f_table_name", length = 256)),
			@AttributeOverride(name = "FGeometryColumn", column = @Column(name = "f_geometry_column", length = 256)),
			@AttributeOverride(name = "coordDimension", column = @Column(name = "coord_dimension")),
			@AttributeOverride(name = "srid", column = @Column(name = "srid")),
			@AttributeOverride(name = "type", column = @Column(name = "type", length = 30)) })
	public GeometryColumnsId getId() {
		return this.id;
	}

	public void setId(GeometryColumnsId id) {
		this.id = id;
	}

}
