package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RasterColumns generated by hbm2java
 */
@Entity
@Table(name = "raster_columns")
public class RasterColumns implements java.io.Serializable {

	private RasterColumnsId id;

	public RasterColumns() {
	}

	public RasterColumns(RasterColumnsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "RTableCatalog", column = @Column(name = "r_table_catalog")),
			@AttributeOverride(name = "RTableSchema", column = @Column(name = "r_table_schema")),
			@AttributeOverride(name = "RTableName", column = @Column(name = "r_table_name")),
			@AttributeOverride(name = "RRasterColumn", column = @Column(name = "r_raster_column")),
			@AttributeOverride(name = "srid", column = @Column(name = "srid")),
			@AttributeOverride(name = "scaleX", column = @Column(name = "scale_x", precision = 17, scale = 17)),
			@AttributeOverride(name = "scaleY", column = @Column(name = "scale_y", precision = 17, scale = 17)),
			@AttributeOverride(name = "blocksizeX", column = @Column(name = "blocksize_x")),
			@AttributeOverride(name = "blocksizeY", column = @Column(name = "blocksize_y")),
			@AttributeOverride(name = "sameAlignment", column = @Column(name = "same_alignment")),
			@AttributeOverride(name = "regularBlocking", column = @Column(name = "regular_blocking")),
			@AttributeOverride(name = "numBands", column = @Column(name = "num_bands")),
			@AttributeOverride(name = "pixelTypes", column = @Column(name = "pixel_types")),
			@AttributeOverride(name = "nodataValues", column = @Column(name = "nodata_values")),
			@AttributeOverride(name = "outDb", column = @Column(name = "out_db")),
			@AttributeOverride(name = "extent", column = @Column(name = "extent")) })
	public RasterColumnsId getId() {
		return this.id;
	}

	public void setId(RasterColumnsId id) {
		this.id = id;
	}

}
