package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Samplecuration generated by hbm2java
 */
@Entity
@Table(name = "samplecuration")
public class Samplecuration implements java.io.Serializable {

	private int samplecurationid;
	private Sample sample;
	private String curationlocation;
	private String curator;
	private Date curationstart;
	private Date curationend;
	private String comments;

	public Samplecuration() {
	}

	public Samplecuration(Sample sample, String curator) {
		
		this.sample = sample;
		this.curator = curator;
	}

	public Samplecuration(Sample sample,
			String curationlocation, String curator, Date curationstart,
			Date curationend, String comments) {
		
		this.sample = sample;
		this.curationlocation = curationlocation;
		this.curator = curator;
		this.curationstart = curationstart;
		this.curationend = curationend;
		this.comments = comments;
	}

	@Id
	@Column(name = "samplecurationid", unique = true, nullable = false)
	@SequenceGenerator(name="samplecuration_samplecurationid_seq",sequenceName="samplecuration_samplecurationid_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="samplecuration_samplecurationid_seq")
	public int getSamplecurationid() {
		return this.samplecurationid;
	}

	public void setSamplecurationid(int samplecurationid) {
		this.samplecurationid = samplecurationid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sampleid", nullable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@Column(name = "curationlocation")
	public String getCurationlocation() {
		return this.curationlocation;
	}

	public void setCurationlocation(String curationlocation) {
		this.curationlocation = curationlocation;
	}

	@Column(name = "curator", nullable = false)
	public String getCurator() {
		return this.curator;
	}

	public void setCurator(String curator) {
		this.curator = curator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "curationstart", length = 29)
	public Date getCurationstart() {
		return this.curationstart;
	}

	public void setCurationstart(Date curationstart) {
		this.curationstart = curationstart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "curationend", length = 29)
	public Date getCurationend() {
		return this.curationend;
	}

	public void setCurationend(Date curationend) {
		this.curationend = curationend;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
