package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sampleresources generated by hbm2java
 */
@Entity
@Table(name = "sampleresources")
public class Sampleresources implements java.io.Serializable {

	private int sampleresourcesid;
	private CvRelatedIdentifiertype cvRelatedIdentifiertype;
	private Sample sample;
	private String resourceidentifier;
	private CvResourceRelationshiptype cvResourceRelationshiptype;
	private Date addeddate;

	public Sampleresources() {
	}

	public Sampleresources(Sample sample,
			String resourceidentifier) {
		
		this.sample = sample;
		this.resourceidentifier = resourceidentifier;
	}

	public Sampleresources(CvRelatedIdentifiertype cvRelatedIdentifiertype, Sample sample,
			String resourceidentifier, CvResourceRelationshiptype cvResourceRelationshiptype,
			Date addeddate) {
		
		this.cvRelatedIdentifiertype = cvRelatedIdentifiertype;
		this.sample = sample;
		this.resourceidentifier = resourceidentifier;
		this.cvResourceRelationshiptype = cvResourceRelationshiptype;
		this.addeddate = addeddate;
	}

	@Id
	@Column(name = "sampleresourcesid", unique = true, nullable = false)
	@SequenceGenerator(name="sampleresources_sampleresourcesid_seq",sequenceName="sampleresources_sampleresourcesid_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="sampleresources_sampleresourcesid_seq")
	public int getSampleresourcesid() {
		return this.sampleresourcesid;
	}

	public void setSampleresourcesid(int sampleresourcesid) {
		this.sampleresourcesid = sampleresourcesid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "resourceidentifertype")
	public CvRelatedIdentifiertype getCvRelatedIdentifiertype() {
		return this.cvRelatedIdentifiertype;
	}

	public void setCvRelatedIdentifiertype(
			CvRelatedIdentifiertype cvRelatedIdentifiertype) {
		this.cvRelatedIdentifiertype = cvRelatedIdentifiertype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sampleid", nullable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@Column(name = "resourceidentifier", nullable = false, length = 250)
	public String getResourceidentifier() {
		return this.resourceidentifier;
	}

	public void setResourceidentifier(String resourceidentifier) {
		this.resourceidentifier = resourceidentifier;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "resourcerelationtype")
	public CvResourceRelationshiptype getCvResourceRelationshiptype() {
		return this.cvResourceRelationshiptype;
	}

	public void setCvResourceRelationshiptype(CvResourceRelationshiptype cvResourceRelationshiptype) {
		this.cvResourceRelationshiptype = cvResourceRelationshiptype;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "addeddate", length = 29)
	public Date getAddeddate() {
		return this.addeddate;
	}

	public void setAddeddate(Date addeddate) {
		this.addeddate = addeddate;
	}

}
