package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Samplingfeatures generated by hbm2java
 */
@Entity
@Table(name = "sampledfeatures")
public class Sampledfeatures implements java.io.Serializable {

	private int featureid;
	private String featuretype;
	private String featurename;
	

	public Sampledfeatures() {
	}


	public Sampledfeatures(String featuretype, String featurename) {
		
		this.setFeaturetype(featuretype);
		this.setFeaturename(featurename);
		
	}

	@Id
	@Column(name = "featureid", unique = true, nullable = false)
	@SequenceGenerator(name="sampledfeatures_featureid_seq",sequenceName="sampledfeatures_featureid_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="sampledfeatures_featureid_seq")
	public int getFeatureid() {
		return this.featureid;
	}

	public void setFeatureid(int featureid) {
		this.featureid = featureid;
	}


	@Column(name = "featuretype", length = 150)
	public String getFeaturetype() {
		return featuretype;
	}


	public void setFeaturetype(String featuretype) {
		this.featuretype = featuretype;
	}

	@Column(name = "featurename", length = 150)
	public String getFeaturename() {
		return featurename;
	}


	public void setFeaturename(String featurename) {
		this.featurename = featurename;
	}

	



}
