package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SampleCollector generated by hbm2java
 */
@Entity
@Table(name = "sample_collector")
public class SampleCollector implements java.io.Serializable {

	private int collectorid;
	private Sample sample;
	private String collector;
	private String collectoridentifier;
	

	public SampleCollector() {
	}

	public SampleCollector(Sample sample, String collector) {	
		this.sample = sample;
		this.collector = collector;
	}

	public SampleCollector(Sample sample, String collector,
			String collectoridentifier) {		
		this.sample = sample;
		this.collector = collector;
		this.collectoridentifier = collectoridentifier;
		
	}

	@Id
	@Column(name = "collectorid", unique = true, nullable = false)
	@SequenceGenerator(name="sample_collector_collectorid_seq",sequenceName="sample_collector_collectorid_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="sample_collector_collectorid_seq")
	public int getCollectorid() {
		return this.collectorid;
	}

	public void setCollectorid(int collectorid) {
		this.collectorid = collectorid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sampleid", nullable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@Column(name = "collector", nullable = false)
	public String getCollector() {
		return this.collector;
	}

	public void setCollector(String collector) {
		this.collector = collector;
	}

	@Column(name = "collectoridentifier")
	public String getCollectoridentifier() {
		return this.collectoridentifier;
	}

	public void setCollectoridentifier(String collectoridentifier) {
		this.collectoridentifier = collectoridentifier;
	}



}
