package org.csiro.igsn.entity.postgres2_0;

// Generated 27/10/2015 10:58:13 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status")
public class Status implements java.io.Serializable {

	private int statusid;
	private String statuscode;
	private String statusabout;
	private String statusdesc;
	private Set<Sample> samplesForPhysicalsamplestatus = new HashSet<Sample>(0);
	private Set<Sample> samplesForRegistrationstatus = new HashSet<Sample>(0);

	public Status() {
	}

	public Status(int statusid, String statuscode) {
		this.statusid = statusid;
		this.statuscode = statuscode;
	}

	public Status(int statusid, String statuscode, String statusabout,
			String statusdesc, Set<Sample> samplesForPhysicalsamplestatus,
			Set<Sample> samplesForRegistrationstatus) {
		this.statusid = statusid;
		this.statuscode = statuscode;
		this.statusabout = statusabout;
		this.statusdesc = statusdesc;
		this.samplesForPhysicalsamplestatus = samplesForPhysicalsamplestatus;
		this.samplesForRegistrationstatus = samplesForRegistrationstatus;
	}

	@Id
	@Column(name = "statusid", unique = true, nullable = false)
	public int getStatusid() {
		return this.statusid;
	}

	public void setStatusid(int statusid) {
		this.statusid = statusid;
	}

	@Column(name = "statuscode", nullable = false, length = 25)
	public String getStatuscode() {
		return this.statuscode;
	}

	public void setStatuscode(String statuscode) {
		this.statuscode = statuscode;
	}

	@Column(name = "statusabout", length = 45)
	public String getStatusabout() {
		return this.statusabout;
	}

	public void setStatusabout(String statusabout) {
		this.statusabout = statusabout;
	}

	@Column(name = "statusdesc", length = 100)
	public String getStatusdesc() {
		return this.statusdesc;
	}

	public void setStatusdesc(String statusdesc) {
		this.statusdesc = statusdesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusByPhysicalsamplestatus")
	public Set<Sample> getSamplesForPhysicalsamplestatus() {
		return this.samplesForPhysicalsamplestatus;
	}

	public void setSamplesForPhysicalsamplestatus(
			Set<Sample> samplesForPhysicalsamplestatus) {
		this.samplesForPhysicalsamplestatus = samplesForPhysicalsamplestatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusByRegistrationstatus")
	public Set<Sample> getSamplesForRegistrationstatus() {
		return this.samplesForRegistrationstatus;
	}

	public void setSamplesForRegistrationstatus(
			Set<Sample> samplesForRegistrationstatus) {
		this.samplesForRegistrationstatus = samplesForRegistrationstatus;
	}

}
